pr

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -17,144 +17,168 @@ pool:
 variables:
   - name: resourceGroupName
     value: 'sd-rg-dev'
+  - name: deploy
+    value: $[ne(Build.Reason, 'PullRequest')]
   - group: 'sd-vm-secrets'
 
 jobs:
-  - job: infrastructure
-    displayName: 'Build artifact and deploy bicep'
-    workspace:
-      clean: all
-    steps:
-      - task: ArchiveFiles@2
-        displayName: 'Archive application'
-        inputs:
-          rootFolderOrFile: '$(Build.SourcesDirectory)' 
-          includeRootFolder: false 
-          archiveType: 'tar' # Options: zip, 7z, tar, wim
-          tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
-          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz' 
-          replaceExistingArchive: true 
-          verbose: true
-   
-      - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz
-        artifact: drop
+  - ${{ if ne(variables.deploy, 'true') }}:
+    - job: compile
+      displayName: 'compile'
+      workspace:
+        clean: all
+      steps:
+        - checkout: self
 
-      - task: AzureCLI@2
-        displayName: 'Run Bicep'
-        name: bicep
-        condition: ${{ parameters.runInfrastructure }}
-        env:
-          VM_PASSWORD: $(SdVMPassword)
-          GIT_PASSWORD: $(gitPassword)
-          GIT_PAT: $(gitPat)
-          personalAccessToken: $(pat)
-        inputs:
-          scriptType: bash
-          azureSubscription: 'c36-sp-dev'
-          scriptLocation: 'inlineScript'
-          failOnStandardError: true
-          inlineScript:  |
-            az group create \
-              --name '${{ variables.resourceGroupName }}' \
-              --location eastus
-  
-            output=$(az deployment group create \
-              --name New-Guid \
-              --resource-group '${{ variables.resourceGroupName }}' \
-              --mode Incremental \
-              --template-file $(Build.SourcesDirectory)/bicep/main.bicep \
-              --parameters $(Build.SourcesDirectory)/bicep/environments/development.parameters.json \
-              --parameters adminPasswordOrKey=$VM_PASSWORD)
-            
-            echo $output
-  
-            sudo apt-get update
-            sudo apt-get install sshpass
-            sudo apt-get install jq
-  
-            sshCmd=$(echo "$output" | jq -r '.properties.outputs.sshCommand.value')
-            sshUsername=$(echo "$output" | jq -r '.properties.outputs.adminUsername.value')
-            hostName=$(echo "$output" | jq -r '.properties.outputs.hostname.value')
+        - task: PowerShell@2
+          inputs: 
+            targetType: 'inline'
+            failOnStderr: true
+            script: |
+              ls
+              cd .\app\
+              python -m py_compile main.py
 
-            [[ -z "${sshCmd// }" ]] && echo "##[error] missing ssh command from bicep output" && exit 1;
+              Write-Host 'Compiled successfully'
 
-            sshpass -p "$VM_PASSWORD" ssh -T -o "StrictHostKeyChecking no" "$sshUsername"@"$hostName" "{ yes | mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-linux-x64-2.211.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "'"'"$(command -v systemctl)"'"'" ]; then ./config.sh --environment --environmentname "'"'"sd-vm-dev"'"'" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/adeane999/ --work _work --projectname 'Stable Diffusion' --auth PAT --token $personalAccessToken --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname "'"'"sd-vm-dev"'"'" --acceptteeeula --agent sdserver --url https://dev.azure.com/adeane999/ --work _work --projectname 'Stable Diffusion' --auth PAT --token $personalAccessToken; ./run.sh; fi; }"
-            
-            if [ !$? ]
-              then
-                echo "##[error] ssh failed to deployment machine";
-                echo $output
-                exit 1;
-            fi
 
-            # echo "##vso[task.setvariable variable=sshCmd;isoutput=true;issecret=true]$sshCmd"
-              
-            #          sudo apt-get install git-all
-            #          git clone https://alexdeane:$GIT_PASSWORD@github.com/Char36/stable-diffusion-flask
-            #          cd ./stable-diffusion-flask/app/
-            
-            #          eval "$(conda shell.bash hook)"
-            #          conda env create -f environment.yaml
-            #          conda activate ldm2
+  - ${{ if eq(variables.deploy, 'true') }}:
+    - job: infrastructure
+      displayName: 'Build artifact and deploy bicep'
+      workspace:
+        clean: all
+      steps:
+        - task: ArchiveFiles@2
+          displayName: 'Archive application'
+          inputs:
+            rootFolderOrFile: '$(Build.SourcesDirectory)' 
+            includeRootFolder: false 
+            archiveType: 'tar' # Options: zip, 7z, tar, wim
+            tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
+            archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz' 
+            replaceExistingArchive: true 
+            verbose: true
     
-            # python -m flask run --port=80 --app main
+        - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).tar.gz
+          artifact: drop
 
-  - deployment: vmDeploy
-    displayName: deploy
-    dependsOn: infrastructure
-    variables:
-      sshCmd: $[ dependencies.infrastructure.outputs['bicep.sshCmd'] ]
-    pool:
-     vmImage: 'ubuntu-latest'
-    environment:
-      name: 'sd-vm-dev'
-      resourceType: VirtualMachine
-    strategy:
-     runOnce:
-#      preDeploy:
-#        steps:
-#          - download: current
-#            artifact: drop
-#
-#          - task: PowerShell@2
-#            displayName: 'Register environment'
-#            env:
-#              VM_PASSWORD: $(pat)
-#            inputs:
-#              pwsh: true
-#              targetType: 'filePath'
-#              filePath: $(Build.SourcesDirectory)/azp/register.ps1
-      deploy:
-        steps:
-          - task: Bash@3
-            inputs:
-              targetType: 'inline'
-              script: |
-                # Modify deployment script based on the app type
-                echo "Starting deployment script run"
-                tar -xf drop.tar.gz -C ./artifact
-                cd ./artifact/app
-                ls
+        - task: AzureCLI@2
+          displayName: 'Run Bicep'
+          name: bicep
+          condition: ${{ parameters.runInfrastructure }}
+          env:
+            VM_PASSWORD: $(SdVMPassword)
+            GIT_PASSWORD: $(gitPassword)
+            GIT_PAT: $(gitPat)
+            personalAccessToken: $(pat)
+          inputs:
+            scriptType: bash
+            azureSubscription: 'c36-sp-dev'
+            scriptLocation: 'inlineScript'
+            failOnStandardError: true
+            inlineScript:  |
+              az group create \
+                --name '${{ variables.resourceGroupName }}' \
+                --location eastus
+    
+              output=$(az deployment group create \
+                --name New-Guid \
+                --resource-group '${{ variables.resourceGroupName }}' \
+                --mode Incremental \
+                --template-file $(Build.SourcesDirectory)/bicep/main.bicep \
+                --parameters $(Build.SourcesDirectory)/bicep/environments/development.parameters.json \
+                --parameters adminPasswordOrKey=$VM_PASSWORD)
+              
+              echo $output
+    
+              sudo apt-get update
+              sudo apt-get install sshpass
+              sudo apt-get install jq
+    
+              sshCmd=$(echo "$output" | jq -r '.properties.outputs.sshCommand.value')
+              sshUsername=$(echo "$output" | jq -r '.properties.outputs.adminUsername.value')
+              hostName=$(echo "$output" | jq -r '.properties.outputs.hostname.value')
 
-                # if [ -z "$sshCmd" ];
-                # then
-                #   echo "##[error] missing ssh command from bicep output"
-                #   exit 1;
-                # fi
+              [[ -z "${sshCmd// }" ]] && echo "##[error] missing ssh command from bicep output" && exit 1;
 
-                # sshpass -p "$SdVMPassword" "$sshCmd"
+              sshpass -p "$VM_PASSWORD" ssh -T -o "StrictHostKeyChecking no" "$sshUsername"@"$hostName" "{ yes | mkdir azagent;cd azagent;curl -fkSL -o vstsagent.tar.gz https://vstsagentpackage.azureedge.net/agent/2.211.1/vsts-agent-linux-x64-2.211.1.tar.gz;tar -zxvf vstsagent.tar.gz; if [ -x "'"'"$(command -v systemctl)"'"'" ]; then ./config.sh --environment --environmentname "'"'"sd-vm-dev"'"'" --acceptteeeula --agent $HOSTNAME --url https://dev.azure.com/adeane999/ --work _work --projectname 'Stable Diffusion' --auth PAT --token $personalAccessToken --runasservice; sudo ./svc.sh install; sudo ./svc.sh start; else ./config.sh --environment --environmentname "'"'"sd-vm-dev"'"'" --acceptteeeula --agent sdserver --url https://dev.azure.com/adeane999/ --work _work --projectname 'Stable Diffusion' --auth PAT --token $personalAccessToken; ./run.sh; fi; }"
+              
+              if [ !$? ]
+                then
+                  echo "##[error] ssh failed to deployment machine";
+                  echo $output
+                  exit 1;
+              fi
 
-                sudo apt-get install libapache2-mod-wsgi-py3  #for python 3
-                sudo apt-get -y install python3 python3-dev
-                sudo apt-get -y install nginx
+              # echo "##vso[task.setvariable variable=sshCmd;isoutput=true;issecret=true]$sshCmd"
                 
-                wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
-                yes no | ./Anaconda3-2022.05-Linux-x86_64.sh
+              #          sudo apt-get install git-all
+              #          git clone https://alexdeane:$GIT_PASSWORD@github.com/Char36/stable-diffusion-flask
+              #          cd ./stable-diffusion-flask/app/
+              
+              #          eval "$(conda shell.bash hook)"
+              #          conda env create -f environment.yaml
+              #          conda activate ldm2
+      
+              # python -m flask run --port=80 --app main
 
-  
-  
-  #                 eval "$(conda shell.bash hook)"
-  #                 conda env create -f environment.yaml
-  #                 conda activate ldm2
+  - ${{ if eq(variables.deploy, 'true') }}:
+    - deployment: vmDeploy
+      displayName: deploy
+      dependsOn: infrastructure
+      variables:
+        sshCmd: $[ dependencies.infrastructure.outputs['bicep.sshCmd'] ]
+      pool:
+      vmImage: 'ubuntu-latest'
+      environment:
+        name: 'sd-vm-dev'
+        resourceType: VirtualMachine
+      strategy:
+      runOnce:
+  #      preDeploy:
+  #        steps:
+  #          - download: current
+  #            artifact: drop
+  #
+  #          - task: PowerShell@2
+  #            displayName: 'Register environment'
+  #            env:
+  #              VM_PASSWORD: $(pat)
+  #            inputs:
+  #              pwsh: true
+  #              targetType: 'filePath'
+  #              filePath: $(Build.SourcesDirectory)/azp/register.ps1
+        deploy:
+          steps:
+            - task: Bash@3
+              inputs:
+                targetType: 'inline'
+                script: |
+                  # Modify deployment script based on the app type
+                  echo "Starting deployment script run"
+                  tar -xf drop.tar.gz -C ./artifact
+                  cd ./artifact/app
+                  ls
 
-  #                 python -m flask run --port=80 --app main
+                  # if [ -z "$sshCmd" ];
+                  # then
+                  #   echo "##[error] missing ssh command from bicep output"
+                  #   exit 1;
+                  # fi
+
+                  # sshpass -p "$SdVMPassword" "$sshCmd"
+
+                  sudo apt-get install libapache2-mod-wsgi-py3  #for python 3
+                  sudo apt-get -y install python3 python3-dev
+                  sudo apt-get -y install nginx
+                  
+                  wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
+                  yes no | ./Anaconda3-2022.05-Linux-x86_64.sh
+
+    
+    
+    #                 eval "$(conda shell.bash hook)"
+    #                 conda env create -f environment.yaml
+    #                 conda activate ldm2
+
+    #                 python -m flask run --port=80 --app main
