aa

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -136,57 +136,57 @@ jobs:
     - deployment: vmDeploy
       displayName: deploy
       dependsOn: infrastructure
-      variables:
-        sshCmd: $[ dependencies.infrastructure.outputs['bicep.sshCmd'] ]
+      # variables:
+      #   sshCmd: $[ dependencies.infrastructure.outputs['bicep.sshCmd'] ]
       pool:
-      vmImage: 'ubuntu-latest'
+        vmImage: 'ubuntu-latest'
       environment:
         name: 'sd-vm-dev'
         resourceType: VirtualMachine
       strategy:
-      runOnce:
-  #      preDeploy:
-  #        steps:
-  #          - download: current
-  #            artifact: drop
-  #
-  #          - task: PowerShell@2
-  #            displayName: 'Register environment'
-  #            env:
-  #              VM_PASSWORD: $(pat)
-  #            inputs:
-  #              pwsh: true
-  #              targetType: 'filePath'
-  #              filePath: $(Build.SourcesDirectory)/azp/register.ps1
-        deploy:
-          steps:
-            - task: Bash@3
-              inputs:
-                targetType: 'inline'
-                script: |
-                  # Modify deployment script based on the app type
-                  echo "Starting deployment script run"
-                  tar -xf drop.tar.gz -C ./artifact
-                  cd ./artifact/app
-                  ls
+        runOnce:
+    #      preDeploy:
+    #        steps:
+    #          - download: current
+    #            artifact: drop
+    #
+    #          - task: PowerShell@2
+    #            displayName: 'Register environment'
+    #            env:
+    #              VM_PASSWORD: $(pat)
+    #            inputs:
+    #              pwsh: true
+    #              targetType: 'filePath'
+    #              filePath: $(Build.SourcesDirectory)/azp/register.ps1
+          deploy:
+            steps:
+              - task: Bash@3
+                inputs:
+                  targetType: 'inline'
+                  script: |
+                    # Modify deployment script based on the app type
+                    echo "Starting deployment script run"
+                    tar -xf drop.tar.gz -C ./artifact
+                    cd ./artifact/app
+                    ls
 
-                  # if [ -z "$sshCmd" ];
-                  # then
-                  #   echo "##[error] missing ssh command from bicep output"
-                  #   exit 1;
-                  # fi
+                    # if [ -z "$sshCmd" ];
+                    # then
+                    #   echo "##[error] missing ssh command from bicep output"
+                    #   exit 1;
+                    # fi
 
-                  # sshpass -p "$SdVMPassword" "$sshCmd"
+                    # sshpass -p "$SdVMPassword" "$sshCmd"
 
-                  sudo apt-get install libapache2-mod-wsgi-py3  #for python 3
-                  sudo apt-get -y install python3 python3-dev
-                  sudo apt-get -y install nginx
-                  
-                  wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
-                  yes no | ./Anaconda3-2022.05-Linux-x86_64.sh
+                    sudo apt-get install libapache2-mod-wsgi-py3  #for python 3
+                    sudo apt-get -y install python3 python3-dev
+                    sudo apt-get -y install nginx
+                    
+                    wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh
+                    yes no | ./Anaconda3-2022.05-Linux-x86_64.sh
 
-    
-    
+      
+      
     #                 eval "$(conda shell.bash hook)"
     #                 conda env create -f environment.yaml
     #                 conda activate ldm2
